steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/lice-ci-cd/live-ci-cd:latest",
        "-t",
        "gcr.io/lice-ci-cd/live-ci-cd:$SHORT_SHA",
        ".",
      ]

  - name: "docker"
    args:
      ["run", "-d", "--name", "goapp", "gcr.io/lice-ci-cd/live-ci-cd:latest"]

  - name: "docker"
    args: ["exec", "goapp", "go", "test"]

  - name: "docker"
    args: ["push", "gcr.io/lice-ci-cd/live-ci-cd:latest"]

  - name: "docker"
    args: ["push", "gcr.io/lice-ci-cd/live-ci-cd:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "go-cloudrun",
        "--image",
        "gcr.io/lice-ci-cd/live-ci-cd:$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
      #
