steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "docker.io/carlosdoki/live-ci-cd:latest",
        "-t",
        "docker.io/carlosdoki/live-ci-cd:$SHORT_SHA",
        ".",
      ]

  - name: "docker"
    args:
      ["run", "-d", "--name", "goapp", "docker.io/carlosdoki/live-ci-cd:latest"]

  - name: "docker"
    args: ["exec", "goapp", "go", "test"]

  - name: "docker"
    args: ["push", "docker.io/carlosdoki/live-ci-cd:latest"]

  - name: "docker"
    args: ["push", "docker.io/carlosdoki/live-ci-cd:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "delpoy",
        "go-cloudrun",
        "--image",
        "docker.io/carlosdoki/live-ci-cd:$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed"
        "--allow-unauthenticated"
      ]
      # 
